### ISSUE TITLE
sdk 崩溃

### ISSUE THREAD

**Issue by lengqingfeng** [wildfirechat/ios-chat#173] opened 2020-04-26 02:59 UTC
WFChatClient sqlite3HashFind 

WFChatClient | sqlite3HashFind + 0
-- | --
1 WFChatClient | sqlite3FindTable + 180
2 WFChatClient | sqlite3LocateTable + 84
3 WFChatClient | selectExpander + 1496
4 WFChatClient | sqlite3WalkSelect + 52
5 WFChatClient | sqlite3SelectPrep + 128
6 WFChatClient | sqlite3Select + 172
7 WFChatClient | yy_reduce + 2972
8 WFChatClient | sqlite3RunParser + 1348
9 WFChatClient | sqlite3LockAndPrepare + 1360
10 WFChatClient | mars::stn::RecyclableStatement::RecyclableStatement(mars::stn::DB2*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int&) + 152
11 WFChatClient | mars::stn::MessageDB::getFriendRequestHead() + 220
12 WFChatClient | mars::stn::PullFriendRequest(long long) + 24
13 WFChatClient | mars::stn::StnCallBack::OnLonglinkIdentifyResponse(AutoBuffer const&, AutoBuffer const&) + 1456
14 WFChatClient | _ZN4mars3stn4$_318__invokeERK10AutoBufferS4_ + 224
15 WFChatClient | LongLinkIdentifyChecker::OnIdentifyResp(AutoBuffer&) + 248
16 WFChatClient | mars::stn::LongLink::__NoopResp(unsigned int, unsigned int, AutoBuffer&, AutoBuffer&, Alarm&, bool&, mars::stn::ConnectProfile&) + 288
17 WFChatClient | mars::stn::LongLink::__RunReadWrite(int, mars::stn::ErrCmdType&, int&, mars::stn::ConnectProfile&) + 13408
18 WFChatClient | mars::stn::LongLink::__Run() + 1664
19 WFChatClient | Thread::start_routine(void*) + 76
20 libsystem_pthread.dylib | __pthread_body + 128
21 libsystem_pthread.dylib | _pthread_start + 44

**Comment by heavyrain2012** [comment] 2020-04-26 22:51
有没有更多更详细的细节提供，只看这个无法看出什么问题

**Comment by lengqingfeng** [comment] 2020-05-06 02:26
#2718975 SIGSEGV
SEGV_ACCERR
WFChatClient pcache1Unpin



WFChatClient | pcache1Unpin + 204
-- | --
1 WFChatClient | pcache1Unpin + 52
2 WFChatClient | sqlite3BtreeCloseCursor + 264
3 WFChatClient | sqlite3VdbeHalt + 148
4 WFChatClient | sqlite3VdbeExec + 58412
5 WFChatClient | sqlite3_step + 2976
6 WFChatClient | mars::stn::RecyclableStatement::executeSelect() + 52
7 WFChatClient | mars::stn::MessageDB::getFriendHead() + 360
8 WFChatClient | mars::stn::PullFriend(long long) + 24
9 WFChatClient | mars::stn::StnCallBack::OnLonglinkIdentifyResponse(AutoBuffer const&, AutoBuffer const&) + 1448
10 WFChatClient | _ZN4mars3stn4$_318__invokeERK10AutoBufferS4_ + 224
11 WFChatClient | LongLinkIdentifyChecker::OnIdentifyResp(AutoBuffer&) + 248
12 WFChatClient | mars::stn::LongLink::__NoopResp(unsigned int, unsigned int, AutoBuffer&, AutoBuffer&, Alarm&, bool&, mars::stn::ConnectProfile&) + 288
13 WFChatClient | mars::stn::LongLink::__RunReadWrite(int, mars::stn::ErrCmdType&, int&, mars::stn::ConnectProfile&) + 13408
14 WFChatClient | mars::stn::LongLink::__Run() + 1664
15 WFChatClient | Thread::start_routine(void*) + 76
16 libsystem_pthread.dylib | 0x0000000199ae6000 + 45760
17 libsystem_pthread.dylib | _pthread_start + 44


libsystem_kernel.dylib | 0x0000000199a6ef2c __psynch_mutexwait
-- | --
1 libsystem_pthread.dylib | 0x0000000199aef180 0x0000000199ae6000
2 libsystem_pthread.dylib | 0x0000000199aef0f0 0x0000000199ae6000
3 WFChatClient | 0x00000001024c7e58 pcache1Create
4 WFChatClient | 0x00000001023f5418 sqlite3BtreeOpen
5 WFChatClient | 0x00000001023dd960 openDatabase
6 WFChatClient | 0x0000000102365fb8 mars::stn::DB2::Open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)
7 WFChatClient | 0x000000010239e098 mars::stn::setAuthInfo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
8 WFChatClient | 0x000000010220d4d0 -[WFCCNetworkService connect:token:]
9 GJHearlthStore | 0x0000000100f03f60 0x0000000100cf4000
10 GJHearlthStore | 0x0000000100f5780c 0x0000000100cf4000
11 libdispatch.dylib | 0x0000000199910a38 __dispatch_call_block_and_release
12 libdispatch.dylib | 0x00000001999117d4 __dispatch_client_callout
13 libdispatch.dylib | 0x00000001998f19e4 __dispatch_main_queue_callback_4CF$VARIANT$armv81
14 CoreFoundation | 0x0000000199e6432c 0x0000000199dba000
15 CoreFoundation | 0x0000000199e5f264 0x0000000199dba000
16 CoreFoundation | 0x0000000199e5e7c0 CFRunLoopRunSpecific
17 GraphicsServices | 0x000000019c05f79c GSEventRunModal
18 UIKitCore | 0x00000001c6929c38 UIApplicationMain
19 GJHearlthStore | 0x0000000100d4e740 0x0000000100cf4000
20 libdyld.dylib | 0x00000001999228e0 _start

**Comment by heavyrain2012** [comment] 2020-05-11 00:25
SDK有个要求，是必须调用完connect之后才能进行别的操作，最好connect在主线程调用，然后如果切换账号，需要先调用disconnect关闭网络和数据库，然后再调用connect，之后才能操作。请确认是不是这个原因

**Comment by lengqingfeng** [comment] 2020-06-02 01:50
没有用,还是偶发崩溃日志.希望解决下.

**Comment by heavyrain2012** [comment] 2020-07-06 02:16
有没有多次调用connect，请查一下代码，都在哪些时机调用了connect

**Comment by heavyrain2012** [comment] 2020-08-05 03:09
Duplicate of #183

**Closed by heavyrain2012** 2020-08-05 03:09 UTC
