### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by LengYi** [wildfirechat/ios-chat#164] opened 2020-04-15 10:19 UTC
IM 不定时崩溃

void mars_boost::signals2::detail::signal1_impl<void, bool, mars_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, mars_boost::function<void (bool)>, mars_boost::function<void (mars_boost::signals2::connection const&, bool)>, mars_boost::signals2::mutex>::do_disconnect<mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > >(mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > const&, mpl_::bool_<false>) + 80

Crashed: mars::stn
0  WFChatClient                   0x109a4f02c void mars_boost::signals2::detail::signal1_impl<void, bool, mars_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, mars_boost::function<void (bool)>, mars_boost::function<void (mars_boost::signals2::connection const&, bool)>, mars_boost::signals2::mutex>::do_disconnect<mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > >(mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > const&, mpl_::bool_<false>) + 80
1  WFChatClient                   0x109a4f020 void mars_boost::signals2::detail::signal1_impl<void, bool, mars_boost::signals2::optional_last_value<void>, int, std::__1::less<int>, mars_boost::function<void (bool)>, mars_boost::function<void (mars_boost::signals2::connection const&, bool)>, mars_boost::signals2::mutex>::do_disconnect<mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > >(mars_boost::_bi::bind_t<void, mars_boost::_mfi::mf1<void, mars::stn::NetCore, bool>, mars_boost::_bi::list2<mars_boost::_bi::value<mars::stn::NetCore*>, mars_boost::arg<1> > > const&, mpl_::bool_<false>) + 68
2  WFChatClient                   0x109a46fb4 mars::stn::NetCore::~NetCore() + 344
3  WFChatClient                   0x109a474d0 mars::stn::NetCore::~NetCore() + 12
4  WFChatClient                   0x109721b18 MessageQueue::__AsyncInvokeHandler(MessageQueue::MessagePost_t const&, MessageQueue::Message&) + 128
5  WFChatClient                   0x109720b00 MessageQueue::RunLoop::Run() + 2584
6  WFChatClient                   0x109721dd0 MessageQueue::MessageQueueCreater::__ThreadRunloop() + 124
7  WFChatClient                   0x109ac771c Thread::start_routine(void*) + 76
8  libsystem_pthread.dylib        0x1b55d9d50 _pthread_start + 128
9  libsystem_pthread.dylib        0x1b55e1c88 thread_start + 8

**Comment by lengqingfeng** [comment] 2020-05-06 02:33
我这边也是,现在80% 崩溃来自这个库,初始化的时候还是,日志应该是查询sql 时候崩溃的,希望官方进口优化下

**Comment by heavyrain2012** [comment] 2020-07-06 02:16
有没有多次调用connect，请查一下代码，都在哪些时机调用了connect

**Comment by heavyrain2012** [comment] 2020-07-06 02:17
另外升级到最新的SDK，看看是否能够解决问题

**Comment by heavyrain2012** [comment] 2020-08-05 03:09
Duplicate of #183

**Closed by heavyrain2012** 2020-08-05 03:09 UTC
