### ISSUE TITLE
野火连接失败，服务器报错如下

### ISSUE THREAD

**Issue by 2822680699** [wildfirechat/ios-chat#200] opened 2020-06-30 14:16 UTC
30/06/2020 22:02:57,130 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 113  - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=null, cause=null, errorMessage=null
30/06/2020 22:02:57,130 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.moquette.server.netty.metrics.MQTTMessageLogger.logMQTTMessage(MQTTMessageLogger.java:53)
30/06/2020 22:02:57,130 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.moquette.server.netty.metrics.MQTTMessageLogger.channelRead(MQTTMessageLogger.java:43)
30/06/2020 22:02:57,130 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
30/06/2020 22:02:57,130 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.moquette.server.netty.metrics.MessageMetricsHandler.channelRead(MessageMetricsHandler.java:54)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:350)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
30/06/2020 22:02:57,131 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
30/06/2020 22:02:57,132 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
30/06/2020 22:02:57,132 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
30/06/2020 22:02:57,132 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
30/06/2020 22:02:57,132 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
30/06/2020 22:02:57,132 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
30/06/2020 22:02:57,132 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
30/06/2020 22:02:57,132 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
30/06/2020 22:02:57,132 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.moquette.server.netty.metrics.BytesMetricsHandler.channelRead(BytesMetricsHandler.java:55)
30/06/2020 22:02:57,132 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
30/06/2020 22:02:57,132 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
30/06/2020 22:02:57,132 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
30/06/2020 22:02:57,132 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
30/06/2020 22:02:57,133 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
30/06/2020 22:02:57,133 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
30/06/2020 22:02:57,133 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
30/06/2020 22:02:57,133 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
30/06/2020 22:02:57,133 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
30/06/2020 22:02:57,133 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
30/06/2020 22:02:57,133 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
30/06/2020 22:02:57,133 [nioEventLoopGroup-3-6] ERROR NettyMQTTHandler 116  - io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
帮忙看一下信息

**Comment by heavyrain2012** [comment] 2020-07-02 13:12
Duplicate of #199

**Closed by heavyrain2012** 2020-07-02 13:12 UTC
